model_family: llava-v1.5-vicuna
model_path: llava-hf/llava-1.5-7b-hf
LoRA:
  r: 32
  alpha: 256
  dropout: 0.05

lr: 1e-4
split: all
data_path: dataset/all_train.json
batch_size: 1
gradient_accumulation_steps: 16
num_epochs: 10
forget_loss: ga
# support ga, gd, kl, po, gapd, gdpd, klpd and popd.
tune_vision_tower: False
tune_mm_projector: True
tune_language_model: False
max_grad_norm: 1.0

save_dir: ckpt_results/llava-7b/${forget_loss}_${lr}_${split}_${num_epochs}
save_steps: 0
overwrite_dir: false
weight_decay: 0.01
save_model: true
eval_while_train: false
eval_only: false
seed: 233
workers: 4
lr_scheduler_type: "cosine"
warmup_ratio: 0.06
max_train_steps: -1
report_to: "wandb"
resume_from_checkpoint: ""
